name: ci-golang-workflow

on: 
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          go: ['1.22.1']
    steps:
      - name: Get repository data
        uses: actions/checkout@v2
      
      - name: Setup go environment
        uses: actions/setup-go@v2 # cria o ambiente go
        with:
          go-version: ${{ matrix.go }}
      
      - name: Test App
        run: go test
      - name: Run App
        run: go run math.go

      - name: Set up QEMU # seta o ambiente docker na maquina
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          push: true
          tags: brendodocker/go-fc-integracao-continua:latest
          